spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME:smg_app}
    password: ${DATABASE_PASSWORD:12345678}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: WARN
    com.smig.smg.receiver: INFO
    org.springframework.web: INFO
