spring:
  datasource:
    url: ${DATABASE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${DATABASE_USERNAME:smg_app}
    password: ${DATABASE_PASSWORD:12345678}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    flyway:
      enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.smig.smg.receiver: DEBUG
